services:
  db:
    container_name: db
    image: db:db
    build: ./db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USERNAME=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-logs:/var/log/postgresql

  app:
    container_name: app
    image: app:app
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    depends_on:
      - db

volumes:
  db-data:
  db-logs:
  node_modules:

networks:
  custom-network:
    driver: bridge
